"""
URL configuration for elearning_platform project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from users.api import UserViewSet, StatusUpdateViewSet
from courses.api import CourseViewSet

router = DefaultRouter()
router.register(r'api/users', UserViewSet)
router.register(r'api/status', StatusUpdateViewSet)
router.register(r'api/courses', CourseViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),

    # Automatically include all the API endpoints generated by the router
    path('', include(router.urls)),

    # For logging in and out of the API interface
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]
